### PR TITLE
allow multiple component instances, improve api, add tests

### PR DESCRIPTION
**Pull request by michaelknoch**
This pr introduces a new component `<HomeIndicator autoHidden={true | false} />` which adds the possibility to disable autoHidden in a deeper component level even if another instance of `HomeIndicator`/`PrefersHomeIndicatorAutoHidden` is already mounted in tree

This approach is similar to #6 but way more leaner, what do you think @jacobp100 @nerdmed ?

### CODE REVIEW

**Comment by jacobp100** [comment]
Does it handle the case where you don't specify the `autoHidden` prop? (`<HomeIndicator />`)

**Comment by michaelknoch** [comment]
yeah, it will show a proptype warning and the indicator will not be not hidden.
It would be awesome if you could test if its behaving as you would expect ;)
@jacobp100 

screen shot 2018-05-29 at 19 24 29

**Comment by jacobp100** [comment]
This is getting awesome! 🎉

**Comment by michaelknoch** [comment]
yeah hope so @jacobp100 
have you already tested this version? Does it work as expected?
Do you have any feedback regarding the code change?

otherwise i will merge and release this soon 🎈

**Comment by jacobp100** [comment]
Awesome that this is merged! 😄

**Pull request merged**
