### PR TITLE
Require double swipe up if there is an app swipe recognizer from the bottom

### PR DESCRIPTION
**Pull request by pvinis**

### CODE REVIEW

**Comment by michaelknoch** [comment]
Hey @pvinis thanks for your contribution. Im currently on vacation. Im going to review and test your code next week when im back in the office

**Comment by michaelknoch** [comment]
Hey @pvinis. Can you provide a reproduction that describes the issue you’re fixing here? The solution looks kind of brittle to me. I think the touch handling of UIKit should be able to handle this if the recognizers are set up correctly.

Feel free to reopen if you think I am wrong

**Comment by pvinis** [comment]
hi, so this was mostly for the app we have, because we have a video playing on landscape, and the scrollbar is on the bottom, so i wanted to disable the home indicator from doing the app swiping basically. i can make a quick demo and reopen this.

**Comment by Gustash** [comment]
@michaelknoch this fixes #23. What makes you feel like this solution is brittle?

**Pull request closed without merging**
